### ISSUE TITLE
Is this open for pull requests?

### ISSUE THREAD

**Issue by Sumo99** [samchasan/thesis_app#12]
Can other people contribute their code towards this project or is it only a school project? Lastly, what does this project do? Is it for putting together by-products?

**Comment by samchasan** [comment]
Yes, this is for putting together a centralized repo for by-products. And currently it is a school project, I'm working on it for my Master's thesis at NYU ITP.  Until I finish school in about 8 weeks I'd like to keep the code my own, it's open mostly so I can get feedback from professors and friends quickly without having to worry about permissions. If you have suggestions I'm all ears!

**Comment by Sumo99** [comment]
Ok, thank you for responding! what do you mean by by-products, can you give an example?

Thank you!
