### ISSUE TITLE
No api key

### ISSUE THREAD

**Issue by koji** [samchasan/thesis_app#9]
https://github.com/samchasan/thesis_app/blob/master/app.js#L16

**Comment by koji** [comment]
```
const yelpToken = process.env.Yelp;
```

```
$ Yelp=jdfslkjvblosjfgpbdjsfosjd npm start
```

**Comment by samchasan** [comment]
I believe this is taken care of in the most recent push: .env is part of .gitignore, and it contains my API keys which are dynamically pulled in
